/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddDsvNamedItemsRequestItemsInner } from '../models/AddDsvNamedItemsRequestItemsInner';
import { HttpFile } from '../http/http';

export class AddDsvNamedItemsRequest {
    /**
    * List of named items representing structural elements of the document.
    */
    'items': Array<AddDsvNamedItemsRequestItemsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AddDsvNamedItemsRequestItemsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddDsvNamedItemsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
