/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddDsvNamedItemsRequestItemsInner {
    /**
    * The display name of the item (e.g., \"Introduction\", \"Chapter 1\").
    */
    'name': string;
    /**
    * Hierarchical level of the item.  Level 0 is the highest (top-level), with increasing numbers for nested structures. 
    */
    'level': number;
    /**
    * Internal reference or identifier for the page this item is associated with.
    */
    'pageName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageName",
            "baseName": "page_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddDsvNamedItemsRequestItemsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
