/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkspaceMemberRoleEnum } from '../models/WorkspaceMemberRoleEnum';
import { HttpFile } from '../http/http';

export class AddMemberRequest {
    /**
    * User id.
    */
    'userId': string;
    'role': WorkspaceMemberRoleEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "WorkspaceMemberRoleEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddMemberRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


