/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkspaceMemberRoleEnum } from '../models/WorkspaceMemberRoleEnum';
import { HttpFile } from '../http/http';

export class AddMemberResponse {
    'memberId'?: string;
    'workspaceId'?: string;
    'role'?: WorkspaceMemberRoleEnum;
    'email'?: string;
    'firstName'?: string;
    'lastName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "memberId",
            "baseName": "member_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "WorkspaceMemberRoleEnum",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddMemberResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


