/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class APILogListResponseResults {
    'id'?: string;
    'url'?: string;
    'status'?: number;
    'requestTime'?: string;
    'responseTime'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "requestTime",
            "baseName": "request_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "responseTime",
            "baseName": "response_time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return APILogListResponseResults.attributeTypeMap;
    }

    public constructor() {
    }
}

