/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppendCLIDataResponseCliPagesInner } from '../models/AppendCLIDataResponseCliPagesInner';
import { HttpFile } from '../http/http';

/**
* Settings of the appended to a document CLI. Name property can be different from what you passed if there were collisions
*/
export class AppendCLIDataResponseCli {
    /**
    * CLI ID appended to the first section.
    */
    'id': string;
    /**
    * The list of the CLI\'s pages you have changed in a result document
    */
    'pages'?: Array<AppendCLIDataResponseCliPagesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "Array<AppendCLIDataResponseCliPagesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppendCLIDataResponseCli.attributeTypeMap;
    }

    public constructor() {
    }
}
