/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppendCLIDataRequestCli } from '../models/AppendCLIDataRequestCli';
import { HttpFile } from '../http/http';

export class AppendCLIDataRequest {
    'cli'?: AppendCLIDataRequestCli;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cli",
            "baseName": "cli",
            "type": "AppendCLIDataRequestCli",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppendCLIDataRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
