/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppendCLIDataResponseBlockMappingImagesInner } from '../models/AppendCLIDataResponseBlockMappingImagesInner';
import { AppendCLIDataResponseBlockMappingPricingTablesInner } from '../models/AppendCLIDataResponseBlockMappingPricingTablesInner';
import { AppendCLIDataResponseBlockMappingTablesInner } from '../models/AppendCLIDataResponseBlockMappingTablesInner';
import { AppendCLIDataResponseBlockMappingTextsInner } from '../models/AppendCLIDataResponseBlockMappingTextsInner';
import { HttpFile } from '../http/http';

/**
* Maps the original names of content blocks from the CLI to their new names in the document. Use the \'new_name\' to target blocks in subsequent API calls.
*/
export class AppendCLIDataResponseBlockMapping {
    /**
    * Mapping for Table blocks.
    */
    'tables'?: Array<AppendCLIDataResponseBlockMappingTablesInner>;
    /**
    * Mapping for Pricing Table blocks.
    */
    'pricingTables'?: Array<AppendCLIDataResponseBlockMappingPricingTablesInner>;
    /**
    * Mapping for Image blocks.
    */
    'images'?: Array<AppendCLIDataResponseBlockMappingImagesInner>;
    /**
    * Mapping for Text blocks.
    */
    'texts'?: Array<AppendCLIDataResponseBlockMappingTextsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tables",
            "baseName": "tables",
            "type": "Array<AppendCLIDataResponseBlockMappingTablesInner>",
            "format": ""
        },
        {
            "name": "pricingTables",
            "baseName": "pricing_tables",
            "type": "Array<AppendCLIDataResponseBlockMappingPricingTablesInner>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<AppendCLIDataResponseBlockMappingImagesInner>",
            "format": ""
        },
        {
            "name": "texts",
            "baseName": "texts",
            "type": "Array<AppendCLIDataResponseBlockMappingTextsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppendCLIDataResponseBlockMapping.attributeTypeMap;
    }

    public constructor() {
    }
}
