/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AppendCLIDataRequestCliPagesInner {
    /**
    * The index of the CLI\'s page you want to change in a result document during appending the CLI
    */
    'index'?: number;
    /**
    * The name you want to apply to the CLI\'s page in a result document during appending the CLI
    */
    'name'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppendCLIDataRequestCliPagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}
