/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AppendCLIDataResponseBlockMappingPricingTablesInner {
    /**
    * The name of the block in the source Content Library Item.
    */
    'originalName'?: string;
    /**
    * The new, unique name of the block in the document after appending.
    */
    'newName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "originalName",
            "baseName": "original_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "newName",
            "baseName": "new_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppendCLIDataResponseBlockMappingPricingTablesInner.attributeTypeMap;
    }

    public constructor() {
    }
}
