/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssignedToRecipientDeliveryMethods } from '../models/AssignedToRecipientDeliveryMethods';
import { RecipientAssignedTo } from '../models/RecipientAssignedTo';
import { RecipientRedirectSettings } from '../models/RecipientRedirectSettings';
import { RecipientsGroupAssignedTo } from '../models/RecipientsGroupAssignedTo';
import { RecipientsGroupAssignedToAllOfMembers } from '../models/RecipientsGroupAssignedToAllOfMembers';
import { HttpFile } from '../http/http';

export class BaseFieldAssignedTo {
    'id'?: string;
    'email'?: string;
    'recipientType'?: string;
    'roles'?: Array<string>;
    'signingOrder'?: number;
    'hasCompleted'?: boolean;
    'firstName'?: string;
    'lastName'?: string;
    'phone'?: string;
    'role'?: string;
    'deliveryMethods'?: AssignedToRecipientDeliveryMethods;
    'redirect'?: RecipientRedirectSettings;
    'type'?: BaseFieldAssignedToTypeEnum;
    'name'?: string;
    'members'?: Array<RecipientsGroupAssignedToAllOfMembers>;

    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "recipient": "RecipientAssignedTo",
        "recipient_group": "RecipientsGroupAssignedTo",
    };

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "recipientType",
            "baseName": "recipient_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "hasCompleted",
            "baseName": "has_completed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "AssignedToRecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "RecipientRedirectSettings",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BaseFieldAssignedToTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<RecipientsGroupAssignedToAllOfMembers>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BaseFieldAssignedTo.attributeTypeMap;
    }

    public constructor() {
        this.type = "BaseFieldAssignedTo" as any;
    }
}

export enum BaseFieldAssignedToTypeEnum {
    Recipient = 'recipient',
    RecipientGroup = 'recipient_group'
}

