/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BaseIdentity {
    /**
    * A recipient\'s email address.
    */
    'email'?: string | null;
    /**
    * A recipient\'s phone number.
    */
    'phone'?: string | null;
    /**
    * A recipient\'s first name. We automatically take the first name from contact data if this field is missed.
    */
    'firstName'?: string;
    /**
    * A recipient\'s last name. We automatically take the last name from contact data if this field is missed.
    */
    'lastName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BaseIdentity.attributeTypeMap;
    }

    public constructor() {
    }
}
