/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BaseEditingSessionResponse {
    /**
    * Internal id of the editing session. Don\'t use it, it\'s not a token.
    */
    'id'?: string;
    /**
    * Email associated with the editing session.
    */
    'email'?: string;
    /**
    * Date and time when the editing session expires.
    */
    'expiresAt'?: Date;
    /**
    * Same value as `token`, token for the embedded editor, aka E-Token. Deprecated — use `token` instead.
    * @deprecated
    */
    'key'?: string;
    /**
    * Token for the embedded editor, aka E-Token. Use it for your Embedding.
    */
    'token'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BaseEditingSessionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
