/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentLibraryItemListResponseResultsInner } from '../models/ContentLibraryItemListResponseResultsInner';
import { HttpFile } from '../http/http';

export class ContentLibraryItemListResponse {
    'results'?: Array<ContentLibraryItemListResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ContentLibraryItemListResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContentLibraryItemListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
