/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseIdentity } from '../models/BaseIdentity';
import { CreateDocumentRecipient } from '../models/CreateDocumentRecipient';
import { CreateDocumentRecipientGroup } from '../models/CreateDocumentRecipientGroup';
import { RecipientDeliveryMethods } from '../models/RecipientDeliveryMethods';
import { RecipientRedirect } from '../models/RecipientRedirect';
import { RecipientVerificationSettings } from '../models/RecipientVerificationSettings';
import { HttpFile } from '../http/http';

export class CreateDocumentActor {
    /**
    * A recipient\'s role in the document from the template. A recipient will be added in CC if a role parameter is not provided.
    */
    'role'?: string;
    /**
    * Set a signing order for a recipient. Learn more: https://developers.pandadoc.com/docs/set-signing-order 
    */
    'signingOrder'?: number;
    /**
    * A recipient\'s email address.
    */
    'email'?: string | null;
    /**
    * A recipient\'s phone number.
    */
    'phone'?: string | null;
    /**
    * A recipient\'s first name. We automatically take the first name from contact data if this field is missed.
    */
    'firstName'?: string;
    /**
    * A recipient\'s last name. We automatically take the last name from contact data if this field is missed.
    */
    'lastName'?: string;
    'deliveryMethods'?: RecipientDeliveryMethods | null;
    'redirect'?: RecipientRedirect;
    'type': CreateDocumentActorTypeEnum;
    'verificationSettings'?: RecipientVerificationSettings | null;
    'name': string;
    'members'?: Array<BaseIdentity>;

    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "recipient": "CreateDocumentRecipient",
        "recipient_group": "CreateDocumentRecipientGroup",
    };

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "RecipientRedirect",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateDocumentActorTypeEnum",
            "format": ""
        },
        {
            "name": "verificationSettings",
            "baseName": "verification_settings",
            "type": "RecipientVerificationSettings",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<BaseIdentity>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentActor.attributeTypeMap;
    }

    public constructor() {
        this.type = CreateDocumentActorTypeEnum.Recipient;
    }
}

export enum CreateDocumentActorTypeEnum {
    Recipient = 'recipient',
    RecipientGroup = 'recipient_group'
}

