/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateUserRequestWorkspaces {
    'workspaceId'?: string;
    'role'?: CreateUserRequestWorkspacesRoleEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "CreateUserRequestWorkspacesRoleEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateUserRequestWorkspaces.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateUserRequestWorkspacesRoleEnum = "Admin" | "Manager" | "Member" | "Collaborator" ;

