/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* You can set an owner of a template as an `email` or `membership_id`.
*/
export class CreateTemplateRequestOwner {
    'membershipId'?: string;
    'email'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "membershipId",
            "baseName": "membership_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        }    ];

    static getAttributeTypeMap() {
        return CreateTemplateRequestOwner.attributeTypeMap;
    }

    public constructor() {
    }
}
