/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyTypeEnum } from '../models/ApiKeyTypeEnum';
import { HttpFile } from '../http/http';

export class CreateApiKeyResponse {
    /**
    * A unique identifier of the user.
    */
    'userId'?: string;
    'type'?: ApiKeyTypeEnum;
    /**
    * A unique identifier of the workspace.
    */
    'workspaceId'?: string;
    /**
    * A New Public API key.
    */
    'key'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiKeyTypeEnum",
            "format": ""
        },
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateApiKeyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


