/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateUserRequestUser } from '../models/CreateUserRequestUser';
import { CreateUserRequestWorkspacesInner } from '../models/CreateUserRequestWorkspacesInner';
import { UserLicenseEnum } from '../models/UserLicenseEnum';
import { HttpFile } from '../http/http';

export class CreateUserRequest {
    'user': CreateUserRequestUser;
    /**
    * Info for adding a user to a workspace(s)
    */
    'workspaces': Array<CreateUserRequestWorkspacesInner>;
    'license': UserLicenseEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "CreateUserRequestUser",
            "format": ""
        },
        {
            "name": "workspaces",
            "baseName": "workspaces",
            "type": "Array<CreateUserRequestWorkspacesInner>",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "UserLicenseEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateUserRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


