/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateNotarizationResponseCreatedBy } from '../models/CreateNotarizationResponseCreatedBy';
import { CreateNotarizationResponseInviteesInner } from '../models/CreateNotarizationResponseInviteesInner';
import { HttpFile } from '../http/http';

export class CreateNotarizationResponse {
    /**
    * A unique identifier of the notarization request.
    */
    'id'?: string;
    /**
    * A name of the notarization request.
    */
    'name'?: string;
    /**
    * Current status of the notarization request.
    */
    'status'?: CreateNotarizationResponseStatusEnum;
    /**
    * A date when a notarization request was created.
    */
    'dateCreated'?: Date;
    /**
    * A date when a notarization session was accepted by notary.
    */
    'dateAccepted'?: Date | null;
    'createdBy'?: CreateNotarizationResponseCreatedBy;
    'invitees'?: Array<CreateNotarizationResponseInviteesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateNotarizationResponseStatusEnum",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateAccepted",
            "baseName": "date_accepted",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "CreateNotarizationResponseCreatedBy",
            "format": ""
        },
        {
            "name": "invitees",
            "baseName": "invitees",
            "type": "Array<CreateNotarizationResponseInviteesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNotarizationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateNotarizationResponseStatusEnum {
    Draft = 'DRAFT',
    Sent = 'SENT',
    WaitingForNotary = 'WAITING_FOR_NOTARY',
    Accepted = 'ACCEPTED',
    Live = 'LIVE',
    Completed = 'COMPLETED',
    Incomplete = 'INCOMPLETE',
    Cancelled = 'CANCELLED'
}

