/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentFieldsField } from '../models/DocumentFieldsField';
import { HttpFile } from '../http/http';

export class CreateDocumentFieldsResponse {
    'fields'?: Array<DocumentFieldsField>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<DocumentFieldsField>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentFieldsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
