/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseIdentity } from '../models/BaseIdentity';
import { HttpFile } from '../http/http';

export class CreateDocumentRecipientGroup {
    /**
    * A recipient\'s role in the document from the template. A recipient will be added in CC if a role parameter is not provided.
    */
    'role'?: string;
    /**
    * Set a signing order for a recipient. Learn more: https://developers.pandadoc.com/docs/set-signing-order 
    */
    'signingOrder'?: number;
    'name': string;
    'type': CreateDocumentRecipientGroupTypeEnum;
    'members'?: Array<BaseIdentity>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateDocumentRecipientGroupTypeEnum",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<BaseIdentity>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentRecipientGroup.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateDocumentRecipientGroupTypeEnum {
    RecipientGroup = 'recipient_group'
}

