/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateNotarizationResponseInviteesInner {
    /**
    * A unique identifier of the invitee.
    */
    'id'?: string;
    /**
    * A invitee\'s email address.
    */
    'email'?: string;
    /**
    * A invitee\'s first name.
    */
    'firstName'?: string;
    /**
    * A invitee\'s last name.
    */
    'lastName'?: string;
    /**
    * A secure link to join a notarization request.
    */
    'notarizationLink'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notarizationLink",
            "baseName": "notarization_link",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNotarizationResponseInviteesInner.attributeTypeMap;
    }

    public constructor() {
    }
}
