/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentFieldsFieldCreate } from '../models/DocumentFieldsFieldCreate';
import { HttpFile } from '../http/http';

export class CreateDocumentFieldsRequest {
    /**
    * An array of fields to place on a document.
    */
    'fields'?: Array<DocumentFieldsFieldCreate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<DocumentFieldsFieldCreate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentFieldsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
