/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateNotarizationRequestInvitation } from '../models/CreateNotarizationRequestInvitation';
import { CreateNotarizationRequestNotary } from '../models/CreateNotarizationRequestNotary';
import { HttpFile } from '../http/http';

export class CreateNotarizationRequest {
    /**
    * ID of the Document for notarization.
    */
    'documentId': string;
    /**
    * Disable all notifications for invitees including email with invitation for notarization. This is useful when you are using alternative delivery methods.
    */
    'disableInviteesNotifications'?: boolean | null;
    'invitation': CreateNotarizationRequestInvitation;
    'notary'?: CreateNotarizationRequestNotary;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "documentId",
            "baseName": "document_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "disableInviteesNotifications",
            "baseName": "disable_invitees_notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "invitation",
            "baseName": "invitation",
            "type": "CreateNotarizationRequestInvitation",
            "format": ""
        },
        {
            "name": "notary",
            "baseName": "notary",
            "type": "CreateNotarizationRequestNotary",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNotarizationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
