/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateNotarizationRequestInvitationInviteesInner } from '../models/CreateNotarizationRequestInvitationInviteesInner';
import { HttpFile } from '../http/http';

export class CreateNotarizationRequestInvitation {
    /**
    * Optional message for invitation email.
    */
    'message'?: string;
    'invitees'?: Array<CreateNotarizationRequestInvitationInviteesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitees",
            "baseName": "invitees",
            "type": "Array<CreateNotarizationRequestInvitationInviteesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNotarizationRequestInvitation.attributeTypeMap;
    }

    public constructor() {
    }
}
