/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateTemplateRequestOwner } from '../models/CreateTemplateRequestOwner';
import { DocumentUpdateRequestTokensInner } from '../models/DocumentUpdateRequestTokensInner';
import { HttpFile } from '../http/http';

export class CreateTemplateFromUrlRequest {
    /**
    * The name of the template.
    */
    'name'?: string;
    /**
    * The ID of the folder where the created template should be stored.
    */
    'folderUuid'?: string;
    'owner'?: CreateTemplateRequestOwner;
    /**
    * You can pass arbitrary data in the key-value format to associate custom information with a template. This information is returned in any API requests for the template details by id.
    */
    'metadata'?: any | null;
    /**
    * Create or initialize multiple CUSTOM variables with their values using tokens/values list. Template\'s predefined variables are read-only. Any attempts to do so will be ignored.
    */
    'tokens'?: Array<DocumentUpdateRequestTokensInner>;
    /**
    * Secure (HTTPS) and publicly accessible URL to the PDF document.
    */
    'url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "folderUuid",
            "baseName": "folder_uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "CreateTemplateRequestOwner",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<DocumentUpdateRequestTokensInner>",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateTemplateFromUrlRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
