/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateNotarizationResponseCreatedBy {
    /**
    * A unique identifier of the user who created a notarization request.
    */
    'userId'?: string;
    /**
    * A user\'s email address.
    */
    'email'?: string;
    /**
    * A user\'s first name.
    */
    'firstName'?: string;
    /**
    * A user\'s last name.
    */
    'lastName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNotarizationResponseCreatedBy.attributeTypeMap;
    }

    public constructor() {
    }
}
