/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentFieldsLayoutPosition } from '../models/DocumentFieldsLayoutPosition';
import { DocumentFieldsLayoutStyle } from '../models/DocumentFieldsLayoutStyle';
import { HttpFile } from '../http/http';

export class DocumentFieldsLayout {
    'page': number;
    'position': DocumentFieldsLayoutPosition;
    'style': DocumentFieldsLayoutStyle;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "DocumentFieldsLayoutPosition",
            "format": ""
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "DocumentFieldsLayoutStyle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentFieldsLayout.attributeTypeMap;
    }

    public constructor() {
    }
}
