/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendManualReminderRequestRemindersInnerEmailCustomization } from '../models/DocumentSendManualReminderRequestRemindersInnerEmailCustomization';
import { RecipientDeliveryMethods } from '../models/RecipientDeliveryMethods';
import { HttpFile } from '../http/http';

export class DocumentSendManualReminderRequestRemindersInner {
    /**
    * Unique identifier of the recipient to receive the reminder.
    */
    'recipientId'?: string;
    'deliveryMethods'?: RecipientDeliveryMethods | null;
    'emailCustomization'?: DocumentSendManualReminderRequestRemindersInnerEmailCustomization;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "emailCustomization",
            "baseName": "email_customization",
            "type": "DocumentSendManualReminderRequestRemindersInnerEmailCustomization",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendManualReminderRequestRemindersInner.attributeTypeMap;
    }

    public constructor() {
    }
}
