/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendRequestSelectedApproversStepsInnerGroupAssigneesInner } from '../models/DocumentSendRequestSelectedApproversStepsInnerGroupAssigneesInner';
import { HttpFile } from '../http/http';

/**
* Group information.
*/
export class DocumentSendRequestSelectedApproversStepsInnerGroup {
    /**
    * Group ID.
    */
    'id': string;
    /**
    * Group type.
    */
    'type': string;
    /**
    * Assignees for the group.
    */
    'assignees': Array<DocumentSendRequestSelectedApproversStepsInnerGroupAssigneesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignees",
            "baseName": "assignees",
            "type": "Array<DocumentSendRequestSelectedApproversStepsInnerGroupAssigneesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendRequestSelectedApproversStepsInnerGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
