/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendRequestForwardingSettings } from '../models/DocumentSendRequestForwardingSettings';
import { DocumentSendRequestSelectedApprovers } from '../models/DocumentSendRequestSelectedApprovers';
import { DocumentSendRequestSender } from '../models/DocumentSendRequestSender';
import { HttpFile } from '../http/http';

export class DocumentSendRequest {
    /**
    * A message that will be sent by email with a link to a document to sign.
    */
    'message'?: string;
    /**
    * Value that will be used as the email subject.
    */
    'subject'?: string;
    /**
    * If set to `true`, disables email notifications for document recipients and the document sender. Also disables scheduled reminders (manual reminders still possible). Doesn\'t affect \"Approve document\" email notification sent to the Approver.
    */
    'silent'?: boolean;
    'sender'?: DocumentSendRequestSender;
    'forwardingSettings'?: DocumentSendRequestForwardingSettings;
    /**
    * Email address that will be used as a reply-to address for the document. To use this parameter, please contact the support team to have it enabled for your account. 
    */
    'replyTo'?: string;
    'selectedApprovers'?: DocumentSendRequestSelectedApprovers;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "silent",
            "baseName": "silent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "DocumentSendRequestSender",
            "format": ""
        },
        {
            "name": "forwardingSettings",
            "baseName": "forwarding_settings",
            "type": "DocumentSendRequestForwardingSettings",
            "format": ""
        },
        {
            "name": "replyTo",
            "baseName": "reply_to",
            "type": "string",
            "format": "email"
        },
        {
            "name": "selectedApprovers",
            "baseName": "selected_approvers",
            "type": "DocumentSendRequestSelectedApprovers",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
