/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendRequestSelectedApproversStepsInner } from '../models/DocumentSendRequestSelectedApproversStepsInner';
import { HttpFile } from '../http/http';

/**
* Configuration for selected approvers.
*/
export class DocumentSendRequestSelectedApprovers {
    /**
    * Approval steps.
    */
    'steps'?: Array<DocumentSendRequestSelectedApproversStepsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<DocumentSendRequestSelectedApproversStepsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendRequestSelectedApprovers.attributeTypeMap;
    }

    public constructor() {
    }
}
