/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentESignDisclosureResult {
    /**
    * Indicates whether the ESign disclosure feature is enabled for the document.
    */
    'isEnabled'?: boolean;
    'companyName'?: string | null;
    /**
    * Rich text (HTML) of the pre-configured ESign disclosure.
    */
    'esignDisclosureText'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isEnabled",
            "baseName": "is_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "companyName",
            "baseName": "company_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "esignDisclosureText",
            "baseName": "esign_disclosure_text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentESignDisclosureResult.attributeTypeMap;
    }

    public constructor() {
    }
}
