/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentSendManualReminder200ResponseResultInnerEmail {
    /**
    * Status of the email reminder attempt (sent or error).
    */
    'status'?: DocumentSendManualReminder200ResponseResultInnerEmailStatusEnum;
    /**
    * Timestamp of when the reminder was sent, in ISO 8601 format.
    */
    'sentAt'?: Date;
    /**
    * Detailed explanation of why the reminder could not be sent, if applicable.
    */
    'detail'?: DocumentSendManualReminder200ResponseResultInnerEmailDetailEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentSendManualReminder200ResponseResultInnerEmailStatusEnum",
            "format": ""
        },
        {
            "name": "sentAt",
            "baseName": "sent_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "DocumentSendManualReminder200ResponseResultInnerEmailDetailEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendManualReminder200ResponseResultInnerEmail.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DocumentSendManualReminder200ResponseResultInnerEmailStatusEnum {
    Sent = 'sent',
    Error = 'error'
}
export enum DocumentSendManualReminder200ResponseResultInnerEmailDetailEnum {
    CantSendReminderToCcRecipient = 'Can\'t send reminder to CC recipient',
    CantSendReminderToRecipientGroup = 'Can\'t send reminder to recipient group',
    CantSendReminderToTheRecipientWhoCompletedTheirPart = 'Can\'t send reminder to the Recipient who completed their part',
    CantSendReminderSigningOrderIsEnabledAndThisRecipientCantSignTheDocumentYet = 'Can\'t send reminder. Signing order is enabled and this Recipient can\'t sign the document yet',
    CantSendReminderEmailDeliveryMethodIsNotSelectedForRecipient = 'Can\'t send reminder. Email delivery method is not selected for recipient',
    CantSendEmailReminderRecipientsMailboxIsUnreachable = 'Can\'t send email reminder. Recipient\'s mailbox is unreachable',
    CantSendEmailReminderToTheRecipientWithNoEmail = 'Can\'t send email reminder to the Recipient with no email',
    CantSendEmailReminderToTheRecipientMoreThanOnceEvery24Hours = 'Can\'t send email reminder to the Recipient more than once every 24 hours',
    CantSendReminderTheDocumentDoesNotContainARecipientWithTheSpecifiedRecipientId = 'Can\'t send reminder. The document does not contain a recipient with the specified recipient ID',
    CantSendReminderEmailMessageContainsPotentiallyMaliciousLinksAndCouldNotBeProcessed = 'Can’t send reminder. Email message contains potentially malicious links and could not be processed'
}

