/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentAuditTrailResponseResultsInner } from '../models/DocumentAuditTrailResponseResultsInner';
import { HttpFile } from '../http/http';

export class DocumentAuditTrailResponse {
    /**
    * Total number of audit trail entries available.
    */
    'count'?: number;
    /**
    * List of audit trail entries returned for the current page.
    */
    'results'?: Array<DocumentAuditTrailResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<DocumentAuditTrailResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentAuditTrailResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
