/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendManualReminder200ResponseResultInnerEmail } from '../models/DocumentSendManualReminder200ResponseResultInnerEmail';
import { DocumentSendManualReminder200ResponseResultInnerEmailCustomization } from '../models/DocumentSendManualReminder200ResponseResultInnerEmailCustomization';
import { DocumentSendManualReminder200ResponseResultInnerSms } from '../models/DocumentSendManualReminder200ResponseResultInnerSms';
import { HttpFile } from '../http/http';

export class DocumentSendManualReminder200ResponseResultInner {
    /**
    * Unique identifier of the recipient.
    */
    'recipientId'?: string;
    'sms'?: DocumentSendManualReminder200ResponseResultInnerSms;
    'email'?: DocumentSendManualReminder200ResponseResultInnerEmail;
    'emailCustomization'?: DocumentSendManualReminder200ResponseResultInnerEmailCustomization;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sms",
            "baseName": "sms",
            "type": "DocumentSendManualReminder200ResponseResultInnerSms",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "DocumentSendManualReminder200ResponseResultInnerEmail",
            "format": ""
        },
        {
            "name": "emailCustomization",
            "baseName": "email_customization",
            "type": "DocumentSendManualReminder200ResponseResultInnerEmailCustomization",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendManualReminder200ResponseResultInner.attributeTypeMap;
    }

    public constructor() {
    }
}
