/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentDetailsResponseRecipients {
    'recipientType'?: string;
    'role'?: string;
    'lastName'?: string;
    'signingOrder'?: any;
    'id'?: string;
    'firstName'?: string;
    'email'?: string;
    'hasCompleted'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recipientType",
            "baseName": "recipient_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasCompleted",
            "baseName": "has_completed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentDetailsResponseRecipients.attributeTypeMap;
    }

    public constructor() {
    }
}

