/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecipientDeliveryMethods } from '../models/RecipientDeliveryMethods';
import { HttpFile } from '../http/http';

export class DocumentSendResponseRecipientsInner {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'recipientType'?: string;
    'email'?: string | null;
    'phone'?: string | null;
    'deliveryMethods'?: RecipientDeliveryMethods | null;
    'signingOrder'?: number | null;
    'sharedLink'?: string;
    'type'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientType",
            "baseName": "recipient_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "sharedLink",
            "baseName": "shared_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendResponseRecipientsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
