/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Set settings for Document and Signature forwarding.
*/
export class DocumentSendRequestForwardingSettings {
    /**
    * Your recipient will be able/not able to forward the document to another email address.
    */
    'forwardingAllowed'?: boolean;
    /**
    * Your recipient will be able/not able to forward the right to fill out all fields (including signature) assigned to them to another email address.
    */
    'forwardingWithReassigningAllowed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "forwardingAllowed",
            "baseName": "forwarding_allowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "forwardingWithReassigningAllowed",
            "baseName": "forwarding_with_reassigning_allowed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendRequestForwardingSettings.attributeTypeMap;
    }

    public constructor() {
    }
}
