/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentCreateRequestOneOf } from '../models/DocumentCreateRequestOneOf';
import { DocumentCreateRequestOneOf1 } from '../models/DocumentCreateRequestOneOf1';
import { HttpFile } from '../http/http';

/**
 * @type DocumentCreateRequest
 * Type
 * @export
 */
export type DocumentCreateRequest = DocumentCreateRequestOneOf | DocumentCreateRequestOneOf1;

/**
* @type DocumentCreateRequestClass
* @export
*/
export class DocumentCreateRequestClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

