/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentCreateResponseLinksInner } from '../models/DocumentCreateResponseLinksInner';
import { DocumentStatusEnum } from '../models/DocumentStatusEnum';
import { HttpFile } from '../http/http';

export class DocumentCreateResponse {
    'id'?: string;
    'name'?: string;
    'status'?: DocumentStatusEnum;
    'dateCreated'?: string;
    'dateModified'?: string;
    'expirationDate'?: string | null;
    'version'?: string | null;
    'uuid'?: string;
    'links'?: Array<DocumentCreateResponseLinksInner>;
    'infoMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentStatusEnum",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "string",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<DocumentCreateResponseLinksInner>",
            "format": ""
        },
        {
            "name": "infoMessage",
            "baseName": "info_message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentCreateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


