/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The method used to deliver reminders (e.g., email, SMS). 
*/
export enum DocumentDeliveryMethodEnum {
    Email = 'email',
    Sms = 'sms'
}
