/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendResponseRecipientsInner } from '../models/DocumentSendResponseRecipientsInner';
import { HttpFile } from '../http/http';

export class DocumentSendResponse {
    'id'?: string;
    'name'?: string;
    'status'?: string;
    'dateCreated'?: string;
    'dateModified'?: string;
    /**
    * Document completion date.
    */
    'dateCompleted'?: string | null;
    'expirationDate'?: string;
    'version'?: string;
    'uuid'?: string;
    'recipients'?: Array<DocumentSendResponseRecipientsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCompleted",
            "baseName": "date_completed",
            "type": "string",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<DocumentSendResponseRecipientsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
