/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentDetailsRecipient } from '../models/DocumentDetailsRecipient';
import { DocumentDetailsRecipientGroup } from '../models/DocumentDetailsRecipientGroup';
import { HttpFile } from '../http/http';

/**
 * @type DocumentDetailsResponseRecipientsInner
 * Type
 * @export
 */
export type DocumentDetailsResponseRecipientsInner = DocumentDetailsRecipient | DocumentDetailsRecipientGroup;

/**
* @type DocumentDetailsResponseRecipientsInnerClass
* @export
*/
export class DocumentDetailsResponseRecipientsInnerClass {
    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "recipient": "DocumentDetailsRecipient",
        "recipient_group": "DocumentDetailsRecipientGroup",
    };
}

