/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentAutoRemindersResponseResultInner } from '../models/DocumentAutoRemindersResponseResultInner';
import { HttpFile } from '../http/http';

export class DocumentAutoRemindersResponse {
    'result'?: Array<DocumentAutoRemindersResponseResultInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<DocumentAutoRemindersResponseResultInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentAutoRemindersResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
