/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecipientDeliveryMethods } from '../models/RecipientDeliveryMethods';
import { RecipientRedirect } from '../models/RecipientRedirect';
import { RecipientVerificationSettings } from '../models/RecipientVerificationSettings';
import { HttpFile } from '../http/http';

export class DocumentRecipientEditRequest {
    /**
    * You cannot use the email of another contact when updating a recipient contact.
    */
    'email'?: string | null;
    'phone'?: string | null;
    'deliveryMethods'?: RecipientDeliveryMethods | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'company'?: string | null;
    'jobTitle'?: string | null;
    'state'?: string | null;
    'streetAddress'?: string | null;
    'city'?: string | null;
    'postalCode'?: string | null;
    'verificationSettings'?: RecipientVerificationSettings | null;
    'redirect'?: RecipientRedirect;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobTitle",
            "baseName": "job_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetAddress",
            "baseName": "street_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "verificationSettings",
            "baseName": "verification_settings",
            "type": "RecipientVerificationSettings",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "RecipientRedirect",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentRecipientEditRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
