/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentRecipientCreateRequest {
    'id': string;
    'kind': DocumentRecipientCreateRequestKindEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "DocumentRecipientCreateRequestKindEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentRecipientCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DocumentRecipientCreateRequestKindEnum = "contact" | "contact_group" ;

