/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum DocumentStatusEnum {
    DocumentDraft = 'document.draft',
    DocumentSent = 'document.sent',
    DocumentCompleted = 'document.completed',
    DocumentUploaded = 'document.uploaded',
    DocumentError = 'document.error',
    DocumentViewed = 'document.viewed',
    DocumentWaitingApproval = 'document.waiting_approval',
    DocumentApproved = 'document.approved',
    DocumentRejected = 'document.rejected',
    DocumentWaitingPay = 'document.waiting_pay',
    DocumentPaid = 'document.paid',
    DocumentVoided = 'document.voided',
    DocumentDeclined = 'document.declined',
    DocumentExternalReview = 'document.external_review'
}
