/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecipientRedirect } from './RecipientRedirect';
import { RicipientDeliveryMethods } from './RicipientDeliveryMethods';
import { HttpFile } from '../http/http';

export class DocumentCreateByTemplateRequestRecipients {
    'email'?: string;
    'phone'?: string;
    'deliveryMethods'?: RicipientDeliveryMethods;
    'firstName'?: string;
    'lastName'?: string;
    'role'?: string;
    'signingOrder'?: number;
    'redirect'?: RecipientRedirect;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RicipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "RecipientRedirect",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentCreateByTemplateRequestRecipients.attributeTypeMap;
    }

    public constructor() {
    }
}

