/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type DocumentOrderingFieldsEnum = "name" | "date_created" | "date_status_changed" | "date_of_last_action" | "date_modified" | "date_sent" | "date_completed" | "date_expiration" | "date_declined" | "status" | "-name" | "-date_created" | "-date_status_changed" | "-date_of_last_action" | "-date_modified" | "-date_sent" | "-date_completed" | "-date_expiration" | "-date_declined" | "-status" ;
