/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Document language code (e.g., \'en-US\', \'fr-FR\').
*/
export enum DocumentLanguageEnum {
    EnUs = 'en-US',
    FrFr = 'fr-FR',
    ItIt = 'it-IT',
    EsEs = 'es-ES',
    NlNl = 'nl-NL',
    DeDe = 'de-DE',
    PtBr = 'pt-BR',
    PtPt = 'pt-PT',
    PlPl = 'pl-PL',
    SvSe = 'sv-SE',
    CsCz = 'cs-CZ',
    DaDk = 'da-DK',
    ElGr = 'el-GR',
    HuHu = 'hu-HU',
    NbNo = 'nb-NO',
    RoRo = 'ro-RO',
    BgBg = 'bg-BG'
}
