/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentESignDisclosureResult } from '../models/DocumentESignDisclosureResult';
import { HttpFile } from '../http/http';

export class DocumentESignDisclosure {
    'result'?: DocumentESignDisclosureResult;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "DocumentESignDisclosureResult",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentESignDisclosure.attributeTypeMap;
    }

    public constructor() {
    }
}
