/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentFieldAnchorPointEnum } from '../models/DocumentFieldAnchorPointEnum';
import { HttpFile } from '../http/http';

export class DocumentFieldsLayoutPosition {
    'offsetX': number;
    'offsetY': number;
    'anchorPoint': DocumentFieldAnchorPointEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offsetX",
            "baseName": "offset_x",
            "type": "number",
            "format": ""
        },
        {
            "name": "offsetY",
            "baseName": "offset_y",
            "type": "number",
            "format": ""
        },
        {
            "name": "anchorPoint",
            "baseName": "anchor_point",
            "type": "DocumentFieldAnchorPointEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentFieldsLayoutPosition.attributeTypeMap;
    }

    public constructor() {
    }
}


