/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentCreateByTemplateRequestFieldsValueValue } from '../models/DocumentCreateByTemplateRequestFieldsValueValue';
import { HttpFile } from '../http/http';

export class DocumentCreateByTemplateRequestFieldsValue {
    'value': DocumentCreateByTemplateRequestFieldsValueValue;
    /**
    * Assign this field to a recipient role. The role must be present in the `recipients` list. 
    */
    'role'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "DocumentCreateByTemplateRequestFieldsValueValue",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentCreateByTemplateRequestFieldsValue.attributeTypeMap;
    }

    public constructor() {
    }
}
