/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentCreateRequestContentLibraryItems } from './DocumentCreateRequestContentLibraryItems';
import { HttpFile } from '../http/http';

export class DocumentCreateRequestContentPlaceholders {
    /**
    * Content placeholder block id
    */
    'blockId'?: string;
    'contentLibraryItems'?: Array<DocumentCreateRequestContentLibraryItems>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockId",
            "baseName": "block_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentLibraryItems",
            "baseName": "content_library_items",
            "type": "Array<DocumentCreateRequestContentLibraryItems>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentCreateRequestContentPlaceholders.attributeTypeMap;
    }

    public constructor() {
    }
}

