/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentSendManualReminder200ResponseResultInnerSms {
    /**
    * Status of the SMS reminder attempt (sent or error).
    */
    'status'?: DocumentSendManualReminder200ResponseResultInnerSmsStatusEnum;
    /**
    * Timestamp of when the reminder was sent, in ISO 8601 format.
    */
    'sentAt'?: Date;
    /**
    * Detailed explanation of why the reminder could not be sent, if applicable.
    */
    'detail'?: DocumentSendManualReminder200ResponseResultInnerSmsDetailEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentSendManualReminder200ResponseResultInnerSmsStatusEnum",
            "format": ""
        },
        {
            "name": "sentAt",
            "baseName": "sent_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "DocumentSendManualReminder200ResponseResultInnerSmsDetailEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendManualReminder200ResponseResultInnerSms.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DocumentSendManualReminder200ResponseResultInnerSmsStatusEnum {
    Sent = 'sent',
    Error = 'error'
}
export enum DocumentSendManualReminder200ResponseResultInnerSmsDetailEnum {
    CantSendReminderToCcRecipient = 'Can\'t send reminder to CC recipient',
    CantSendReminderToRecipientGroup = 'Can\'t send reminder to recipient group',
    CantSendReminderToTheRecipientWhoCompletedTheirPart = 'Can\'t send reminder to the Recipient who completed their part',
    CantSendReminderSigningOrderIsEnabledAndThisRecipientCantSignTheDocumentYet = 'Can\'t send reminder. Signing order is enabled and this Recipient can\'t sign the document yet',
    CantSendReminderSmsDeliveryMethodIsNotSelectedForRecipient = 'Can\'t send reminder. SMS delivery method is not selected for recipient',
    CantSendSmsReminderConfirmationOfRecipientConsentIsRequiredAdminShouldAccessWorkspaceSettingsToCertify = 'Can\'t send SMS reminder. Confirmation of recipient consent is required. Admin should access workspace settings to certify',
    CantSendSmsReminderToTheRecipientMoreThanOnceEvery24Hours = 'Can\'t send SMS reminder to the Recipient more than once every 24 hours',
    CantSendSmsReminderToTheRecipientWithNoPhoneNumber = 'Can\'t send SMS reminder to the Recipient with no phone number',
    CantSendSmsReminderToTheRecipientWithInvalidPhoneNumber = 'Can\'t send SMS reminder to the Recipient with invalid phone number',
    CantSendReminderTheDocumentDoesNotContainARecipientWithTheSpecifiedRecipientId = 'Can\'t send reminder. The document does not contain a recipient with the specified recipient ID'
}

