/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Recipient Group Member
*/
export class DocumentDetailsRecipientGroupMember {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'email'?: string | null;
    'sharedLink'?: string;
    'avatar'?: string | null;
    'signatureDate'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "sharedLink",
            "baseName": "shared_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "signatureDate",
            "baseName": "signature_date",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentDetailsRecipientGroupMember.attributeTypeMap;
    }

    public constructor() {
    }
}
