/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentFieldTypeEnum } from '../models/DocumentFieldTypeEnum';
import { DocumentFieldsFieldAssignedTo } from '../models/DocumentFieldsFieldAssignedTo';
import { DocumentFieldsLayout } from '../models/DocumentFieldsLayout';
import { HttpFile } from '../http/http';

export class DocumentFieldsField {
    'uuid'?: string;
    'name'?: string;
    'title'?: string;
    'value'?: any | null;
    'fieldId'?: string;
    'type'?: DocumentFieldTypeEnum;
    'placeholder'?: string;
    'assignedTo'?: DocumentFieldsFieldAssignedTo;
    'layout'?: DocumentFieldsLayout;
    'sectionUuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        },
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DocumentFieldTypeEnum",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedTo",
            "baseName": "assigned_to",
            "type": "DocumentFieldsFieldAssignedTo",
            "format": ""
        },
        {
            "name": "layout",
            "baseName": "layout",
            "type": "DocumentFieldsLayout",
            "format": ""
        },
        {
            "name": "sectionUuid",
            "baseName": "section_uuid",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return DocumentFieldsField.attributeTypeMap;
    }

    public constructor() {
    }
}


