/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentAuditTrailResponseResultsInnerUser } from '../models/DocumentAuditTrailResponseResultsInnerUser';
import { HttpFile } from '../http/http';

/**
* Represents a single audit trail event for a document.
*/
export class DocumentAuditTrailResponseResultsInner {
    /**
    * Unique identifier of the audit trail entry.
    */
    'id'?: string;
    'user'?: DocumentAuditTrailResponseResultsInnerUser;
    /**
    * Numeric code representing the type of action performed. Possible values:  | Integer Value | String Representation | |---------------|---------------------------------------------| | 1 | new document | | 2 | new revision | | 3 | approval request | | 4 | approved | | 5 | rejected | | 6 | sent | | 7 | completed by all | | 8 | viewed | | 9 | completed | | 10 | waiting pay | | 11 | paid | | 12 | forwarded | | 13 | expired | | 14 | bank account submitted | | 15 | bank account verified | | 16 | payment submitted | | 17 | payment failed | | 18 | completed manually | | 19 | expired manually | | 20 | paid manually | | 21 | approval deleted | | 22 | approval forced | | 23 | reassigned | | 24 | recipient edited | | 25 | recipient added | | 26 | recipient deleted | | 27 | declined manually | | 28 | approval step skipped | | 29 | suggest edits | | 43 | declined | | 44 | partly paid | | 45 | partly paid manually | | 47 | recipient verification with kba passed | | 48 | recipient verification with id passed | | 49 | recipient verification with text sms passed | | 50 | recipient verification with passcode passed | | 51 | recipient verification with kba failed | | 52 | recipient verification with id failed | | 53 | recipient verification with text sms failed | | 54 | recipient verification with passcode failed | | 55 | recipient signed with QES | | 56 | QES completed | | 57 | recipient QES attempt started | | 58 | recipient QES attempt expired | | 59 | Optional item in quote selected | | 60 | Optional item in quote deselected | | 61 | Item quantity in quote changed | | 62 | Item quantity in pricing table changed | | 63 | Optional item in pricing table selected | | 64 | Optional item in pricing table deselected | | 65 | Section item in pricing table selected (one of) | | 66 | Optional section in quote selected | | 67 | Optional section in quote deselected | | 68 | Section quantity in quote changed | 
    */
    'action'?: number;
    /**
    * Optional reason or explanation for the action.
    */
    'reason'?: string | null;
    /**
    * Timestamp when the action was performed (in ISO 8601 format).
    */
    'dateCreated'?: Date;
    /**
    * The IP address from which the action was performed. If a sandbox API key is used, this will be \"hidden\".
    */
    'ipAddress'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "DocumentAuditTrailResponseResultsInnerUser",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "number",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "ipAddress",
            "baseName": "ip_address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentAuditTrailResponseResultsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
