/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendRequestSelectedApproversGroupAssignees } from './DocumentSendRequestSelectedApproversGroupAssignees';
import { HttpFile } from '../http/http';

/**
* Group information
*/
export class DocumentSendRequestSelectedApproversGroup {
    /**
    * Group ID
    */
    'id': string;
    /**
    * Group type
    */
    'type': string;
    /**
    * Assignees for the group
    */
    'assignees': Array<DocumentSendRequestSelectedApproversGroupAssignees>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignees",
            "baseName": "assignees",
            "type": "Array<DocumentSendRequestSelectedApproversGroupAssignees>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendRequestSelectedApproversGroup.attributeTypeMap;
    }

    public constructor() {
    }
}

