/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type DocumentStatusEnum = "document.draft" | "document.sent" | "document.completed" | "document.uploaded" | "document.error" | "document.viewed" | "document.waiting_approval" | "document.approved" | "document.rejected" | "document.waiting_pay" | "document.paid" | "document.voided" | "document.declined" | "document.external_review" ;
