/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentAutoRemindersResponseResultInner {
    /**
    * Unique identifier of the recipient.
    */
    'recipientId'?: string;
    /**
    * Status of the reminder attempt (sent, error, scheduled).
    */
    'status'?: DocumentAutoRemindersResponseResultInnerStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentAutoRemindersResponseResultInnerStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentAutoRemindersResponseResultInner.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DocumentAutoRemindersResponseResultInnerStatusEnum {
    Sent = 'sent',
    Error = 'error',
    Scheduled = 'scheduled'
}

