/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableRequest } from './PricingTableRequest';
import { HttpFile } from '../http/http';

export class DocumentCreateRequestContentLibraryItems {
    /**
    * Content library item id
    */
    'id'?: string;
    'pricingTables'?: Array<PricingTableRequest>;
    'fields'?: any;
    'recipients'?: Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricingTables",
            "baseName": "pricing_tables",
            "type": "Array<PricingTableRequest>",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentCreateRequestContentLibraryItems.attributeTypeMap;
    }

    public constructor() {
    }
}

