/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentSendManualReminder200ResponseResultInner } from '../models/DocumentSendManualReminder200ResponseResultInner';
import { HttpFile } from '../http/http';

export class DocumentSendManualReminder200Response {
    'result'?: Array<DocumentSendManualReminder200ResponseResultInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<DocumentSendManualReminder200ResponseResultInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentSendManualReminder200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
