/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Number code for the target document status. See notes for the codes corresponding to each status.
*/
export enum DocumentStatusChangeRequestStatusEnum {
    NUMBER_2 = 2,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12
}
