/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentsFolderCreateRequest {
    /**
    * Name the folder for the Documents you are creating.
    */
    'name': string;
    /**
    * ID of the parent folder. To create a new folder in the root folder, remove this parameter in the request.
    */
    'parentUuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentUuid",
            "baseName": "parent_uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentsFolderCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
