/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum DocumentFieldTypeEnum {
    Checkbox = 'checkbox',
    CollectFile = 'collect_file',
    Date = 'date',
    Dropdown = 'dropdown',
    Initials = 'initials',
    PaymentDetails = 'payment_details',
    RadioButtons = 'radio_buttons',
    Signature = 'signature',
    Stamp = 'stamp',
    Text = 'text'
}
