/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The value to pre-fill the field with. The type of the value depends on the field type in the template. For example, for a checkbox field, you can pass a boolean value, and for a date field, you can pass a date string in RFC 3339 format (e.g., 2019-12-31T00:00:00.000Z). 
*/
/**
 * @type DocumentCreateByTemplateRequestFieldsValueValue
 * Type
 * @export
 */
export type DocumentCreateByTemplateRequestFieldsValueValue = boolean | number | string;

/**
* @type DocumentCreateByTemplateRequestFieldsValueValueClass
    * The value to pre-fill the field with. The type of the value depends on the field type in the template. For example, for a checkbox field, you can pass a boolean value, and for a date field, you can pass a date string in RFC 3339 format (e.g., 2019-12-31T00:00:00.000Z). 
* @export
*/
export class DocumentCreateByTemplateRequestFieldsValueValueClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


