/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentDocxExportStatusEnum } from '../models/DocumentDocxExportStatusEnum';
import { DocxExportTaskResponseAllOfDocxItems } from '../models/DocxExportTaskResponseAllOfDocxItems';
import { HttpFile } from '../http/http';

export class DocxExportTaskResponse {
    /**
    * Export task id.
    */
    'id': string;
    /**
    * Document id.
    */
    'documentId': string;
    'status': DocumentDocxExportStatusEnum;
    /**
    * DOCX files result URLs with their names.
    */
    'docxItems'?: Array<DocxExportTaskResponseAllOfDocxItems>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentId",
            "baseName": "document_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentDocxExportStatusEnum",
            "format": ""
        },
        {
            "name": "docxItems",
            "baseName": "docx_items",
            "type": "Array<DocxExportTaskResponseAllOfDocxItems>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocxExportTaskResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


