/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* List of download links and section item titles of the document.
*/
export class DocxExportTaskResponseAllOfDocxItems {
    /**
    * Document Section Item title.
    */
    'sectionTitle'?: string | null;
    /**
    * The url for downloading the DOCX file.
    */
    'url'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sectionTitle",
            "baseName": "section_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return DocxExportTaskResponseAllOfDocxItems.attributeTypeMap;
    }

    public constructor() {
    }
}
