/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseFieldAssignedTo } from '../models/BaseFieldAssignedTo';
import { HttpFile } from '../http/http';

export class Dropdown {
    'uuid'?: string;
    /**
    * Name of a field
    */
    'name'?: string;
    'title'?: string;
    /**
    * Placeholder of a field
    */
    'placeholder'?: string;
    'assignedTo'?: BaseFieldAssignedTo;
    'fieldId'?: string;
    'type'?: DropdownTypeEnum;
    /**
    * Value of the Dropdown field.
    */
    'value'?: string;
    'mergeField'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedTo",
            "baseName": "assigned_to",
            "type": "BaseFieldAssignedTo",
            "format": ""
        },
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DropdownTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "mergeField",
            "baseName": "merge_field",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Dropdown.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DropdownTypeEnum {
    Dropdown = 'dropdown'
}

