/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EditingSessionRequest {
    /**
    * Email of the user to create the editing session for
    */
    'email': string;
    /**
    * Lifetime of the E-Token in seconds.
    */
    'lifetime'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "lifetime",
            "baseName": "lifetime",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return EditingSessionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
