/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseFieldAssignedTo } from '../models/BaseFieldAssignedTo';
import { Checkbox } from '../models/Checkbox';
import { CollectFile } from '../models/CollectFile';
import { Dropdown } from '../models/Dropdown';
import { Initials } from '../models/Initials';
import { ModelDate } from '../models/ModelDate';
import { Payment } from '../models/Payment';
import { RadioButtons } from '../models/RadioButtons';
import { Signature } from '../models/Signature';
import { Stamp } from '../models/Stamp';
import { Text } from '../models/Text';
import { HttpFile } from '../http/http';

export class Field {
    'uuid'?: string;
    /**
    * Name of a field
    */
    'name'?: string;
    'title'?: string;
    /**
    * Placeholder of a field
    */
    'placeholder'?: string;
    'assignedTo'?: BaseFieldAssignedTo;
    'fieldId'?: string;
    'type'?: FieldTypeEnum;
    /**
    * Value of the Text field.
    */
    'value'?: string;
    'mergeField'?: string | null;

    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "checkbox": "Checkbox",
        "collect_file": "CollectFile",
        "date": "ModelDate",
        "dropdown": "Dropdown",
        "initials": "Initials",
        "payment": "Payment",
        "radio_buttons": "RadioButtons",
        "signature": "Signature",
        "stamp": "Stamp",
        "text": "Text",
    };

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedTo",
            "baseName": "assigned_to",
            "type": "BaseFieldAssignedTo",
            "format": ""
        },
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "FieldTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "mergeField",
            "baseName": "merge_field",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Field.attributeTypeMap;
    }

    public constructor() {
        this.type = "Field" as any;
    }
}

export enum FieldTypeEnum {
    Checkbox = 'checkbox',
    CollectFile = 'collect_file',
    Date = 'date',
    Dropdown = 'dropdown',
    Initials = 'initials',
    PaymentDetails = 'payment_details',
    RadioButtons = 'radio_buttons',
    Signature = 'signature',
    Stamp = 'stamp',
    Text = 'text'
}

