/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FormListResponseResultsInner } from '../models/FormListResponseResultsInner';
import { HttpFile } from '../http/http';

export class FormListResponse {
    'results'?: Array<FormListResponseResultsInner>;
    'hasNextPage'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<FormListResponseResultsInner>",
            "format": ""
        },
        {
            "name": "hasNextPage",
            "baseName": "has_next_page",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FormListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
