/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LinkedObjectChild } from '../models/LinkedObjectChild';
import { HttpFile } from '../http/http';

export class LinkedObjectCreateResponse {
    /**
    * Linked object identifier (link_id).
    */
    'id'?: string;
    /**
    * CRM name (lowercase).  See the list of available providers: https://developers.pandadoc.com/reference/link-service#examples-of-the-most-popular-crms 
    */
    'provider'?: string;
    /**
    * Entity type.  See the available entity types: https://developers.pandadoc.com/reference/link-service#examples-of-the-most-popular-crms 
    */
    'entityType'?: string;
    /**
    * Entity unique identifier. The system validates if the entity exists.
    */
    'entityId'?: string;
    'children'?: Array<LinkedObjectChild>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityId",
            "baseName": "entity_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<LinkedObjectChild>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LinkedObjectCreateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
