/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListDocuments403ResponseLinksInner } from '../models/ListDocuments403ResponseLinksInner';
import { HttpFile } from '../http/http';

export class ListDocuments403Response {
    'type'?: string;
    'detail'?: string;
    /**
    * Human-readable explanation of the permission error.
    */
    'infoMessage'?: string;
    /**
    * Optional links related to the error (e.g. a status endpoint).
    */
    'links'?: Array<ListDocuments403ResponseLinksInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "infoMessage",
            "baseName": "info_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<ListDocuments403ResponseLinksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListDocuments403Response.attributeTypeMap;
    }

    public constructor() {
    }
}
