/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListWorkspacesResponseResultsInner {
    /**
    * A unique identifier of a workspace in a organization
    */
    'id'?: string;
    /**
    * A workspace\'s name
    */
    'name'?: string;
    /**
    * A workspace\'s date creation
    */
    'dateCreated'?: string;
    /**
    * A owner\'s email address
    */
    'owner'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string",
            "format": "email"
        }    ];

    static getAttributeTypeMap() {
        return ListWorkspacesResponseResultsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
