/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListWorkspacesResponseResultsInner } from '../models/ListWorkspacesResponseResultsInner';
import { HttpFile } from '../http/http';

export class ListWorkspacesResponse {
    /**
    * A number of workspaces
    */
    'total'?: number;
    'results'?: Array<ListWorkspacesResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ListWorkspacesResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListWorkspacesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
