/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListSmsOptOutChangelogResponseResultsInner {
    'phoneNumber'?: string;
    'status'?: ListSmsOptOutChangelogResponseResultsInnerStatusEnum;
    'optOutChanged'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ListSmsOptOutChangelogResponseResultsInnerStatusEnum",
            "format": ""
        },
        {
            "name": "optOutChanged",
            "baseName": "opt_out_changed",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ListSmsOptOutChangelogResponseResultsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ListSmsOptOutChangelogResponseResultsInnerStatusEnum {
    OptIn = 'opt-in',
    OptOut = 'opt-out'
}

