/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListUsersResponseResultsInner } from '../models/ListUsersResponseResultsInner';
import { HttpFile } from '../http/http';

export class ListUsersResponse {
    /**
    * A number of users
    */
    'total'?: number;
    'results'?: Array<ListUsersResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ListUsersResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListUsersResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
