/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListNotaries400ResponseDetailsInner } from '../models/ListNotaries400ResponseDetailsInner';
import { HttpFile } from '../http/http';

export class ListNotaries429Response {
    'code'?: string;
    'details'?: Array<ListNotaries400ResponseDetailsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<ListNotaries400ResponseDetailsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListNotaries429Response.attributeTypeMap;
    }

    public constructor() {
    }
}
