/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListNotariesResponseResultsInner } from '../models/ListNotariesResponseResultsInner';
import { HttpFile } from '../http/http';

export class ListNotariesResponse {
    /**
    * Array of notary objects
    */
    'results'?: Array<ListNotariesResponseResultsInner>;
    /**
    * Total number of notaries matching the criteria
    */
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ListNotariesResponseResultsInner>",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListNotariesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
