/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MemberDetailsResponse {
    /**
    * A unique identifier of the user in the organization.
    */
    'userId'?: string;
    /**
    * A unique identifier of the user in the workspace.
    */
    'membershipId'?: string;
    /**
    * A user's email address.
    */
    'email'?: string;
    /**
    * A user's first name.
    */
    'firstName'?: string;
    /**
    * A user's last name.
    */
    'lastName'?: string;
    /**
    * A boolean value that identifies if a member is active in the workspace.
    */
    'isActive'?: boolean;
    /**
    * A name of the user's current active workspace.
    */
    'workspace'?: string;
    /**
    * A unique identifier of the user's current active workspace.
    */
    'workspaceName'?: string;
    /**
    * A boolean value that identifies if the email is verified.
    */
    'emailsVerified'?: boolean;
    /**
    * A member's role in the workspace.
    */
    'role'?: string;
    /**
    * A user license in the organization.
    */
    'userLicense'?: string;
    /**
    * A date when a member was added to the workspace.
    */
    'dateCreated'?: string;
    /**
    * Last modified date of a member.
    */
    'dateModified'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "membershipId",
            "baseName": "membership_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "workspace",
            "baseName": "workspace",
            "type": "string",
            "format": ""
        },
        {
            "name": "workspaceName",
            "baseName": "workspace_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailsVerified",
            "baseName": "emails_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "userLicense",
            "baseName": "user_license",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MemberDetailsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

