/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MemberDetailsResponse } from './MemberDetailsResponse';
import { HttpFile } from '../http/http';

export class MemberListResponse {
    'results'?: Array<MemberDetailsResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<MemberDetailsResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MemberListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

