/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NotarizationRequestDetailsResponseRecording {
    /**
    * Secure URL to download video recording of the notarization session.
    */
    'url'?: string;
    /**
    * Name of the video recording file.
    */
    'name'?: string;
    /**
    * Size of the video recording file in bytes.
    */
    'size'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotarizationRequestDetailsResponseRecording.attributeTypeMap;
    }

    public constructor() {
    }
}
