/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PricingTableRequestOptionsDiscount {
    'isGlobal'?: boolean;
    'type'?: PricingTableRequestOptionsDiscountTypeEnum;
    'name'?: string;
    'value'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isGlobal",
            "baseName": "is_global",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PricingTableRequestOptionsDiscountTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestOptionsDiscount.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PricingTableRequestOptionsDiscountTypeEnum = "absolute" | "percent" ;

