/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTablesResponseItems } from './PricingTablesResponseItems';
import { PricingTablesResponseSummary } from './PricingTablesResponseSummary';
import { HttpFile } from '../http/http';

export class PricingTablesResponseTables {
    'name'?: string;
    'id'?: string;
    'total'?: string;
    'isIncludedInTotal'?: boolean;
    'summary'?: PricingTablesResponseSummary;
    'items'?: Array<PricingTablesResponseItems>;
    'currency'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "isIncludedInTotal",
            "baseName": "is_included_in_total",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "PricingTablesResponseSummary",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<PricingTablesResponseItems>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTablesResponseTables.attributeTypeMap;
    }

    public constructor() {
    }
}

