/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableRequestRowOptions } from './PricingTableRequestRowOptions';
import { HttpFile } from '../http/http';

export class PricingTableRequestRows {
    'options'?: PricingTableRequestRowOptions;
    'data'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "options",
            "baseName": "options",
            "type": "PricingTableRequestRowOptions",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestRows.attributeTypeMap;
    }

    public constructor() {
    }
}

