/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableResponseItems } from './PricingTableResponseItems';
import { PricingTableResponseSummary } from './PricingTableResponseSummary';
import { HttpFile } from '../http/http';

export class PricingTableResponse {
    'name'?: string;
    'id'?: string;
    'total'?: string;
    'isIncludedInTotal'?: boolean;
    'summary'?: PricingTableResponseSummary;
    'items'?: Array<PricingTableResponseItems>;
    'currency'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "isIncludedInTotal",
            "baseName": "is_included_in_total",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "PricingTableResponseSummary",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<PricingTableResponseItems>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

