/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PricingTablesResponseSummary {
    'subtotal'?: string;
    'total'?: string;
    'discount'?: string;
    'tax'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subtotal",
            "baseName": "subtotal",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "string",
            "format": ""
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTablesResponseSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

