/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PricingTableResponseSummary {
    'subtotal'?: string | null;
    'total'?: string | null;
    'discount'?: string | null;
    'tax'?: string | null;
    'fee'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subtotal",
            "baseName": "subtotal",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "string",
            "format": ""
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "string",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableResponseSummary.attributeTypeMap;
    }

    public constructor() {
    }
}
