/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTablesResponseDiscount } from './PricingTablesResponseDiscount';
import { PricingTablesResponseOptions } from './PricingTablesResponseOptions';
import { HttpFile } from '../http/http';

export class PricingTablesResponseItems {
    'id'?: string;
    'sku'?: string;
    'qty'?: string;
    'name'?: string;
    'cost'?: string;
    'price'?: string;
    'description'?: string;
    'customFields'?: any;
    'customColumns'?: any;
    'discount'?: PricingTablesResponseDiscount;
    'taxFirst'?: PricingTablesResponseDiscount;
    'taxSecond'?: PricingTablesResponseDiscount;
    'subtotal'?: string;
    'options'?: PricingTablesResponseOptions;
    'salePrice'?: string;
    'taxes'?: any;
    'discounts'?: any;
    'fees'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customColumns",
            "baseName": "custom_columns",
            "type": "any",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "PricingTablesResponseDiscount",
            "format": ""
        },
        {
            "name": "taxFirst",
            "baseName": "tax_first",
            "type": "PricingTablesResponseDiscount",
            "format": ""
        },
        {
            "name": "taxSecond",
            "baseName": "tax_second",
            "type": "PricingTablesResponseDiscount",
            "format": ""
        },
        {
            "name": "subtotal",
            "baseName": "subtotal",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "PricingTablesResponseOptions",
            "format": ""
        },
        {
            "name": "salePrice",
            "baseName": "sale_price",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "any",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "any",
            "format": ""
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTablesResponseItems.attributeTypeMap;
    }

    public constructor() {
    }
}

