/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableResponse } from '../models/PricingTableResponse';
import { QuoteResponse } from '../models/QuoteResponse';
import { HttpFile } from '../http/http';

export class PricingResponse {
    'tables'?: Array<PricingTableResponse>;
    'quotes'?: Array<QuoteResponse>;
    'total'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tables",
            "baseName": "tables",
            "type": "Array<PricingTableResponse>",
            "format": ""
        },
        {
            "name": "quotes",
            "baseName": "quotes",
            "type": "Array<QuoteResponse>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
