/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableRequestSectionsInnerRowsInner } from '../models/PricingTableRequestSectionsInnerRowsInner';
import { HttpFile } from '../http/http';

export class PricingTableRequestSectionsInner {
    'title': string;
    '_default'?: boolean;
    'multichoiceEnabled'?: boolean;
    'rows'?: Array<PricingTableRequestSectionsInnerRowsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "multichoiceEnabled",
            "baseName": "multichoice_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rows",
            "baseName": "rows",
            "type": "Array<PricingTableRequestSectionsInnerRowsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestSectionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
