/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTablesResponseTables } from './PricingTablesResponseTables';
import { HttpFile } from '../http/http';

export class PricingTablesResponse {
    'tables'?: Array<PricingTablesResponseTables>;
    'total'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tables",
            "baseName": "tables",
            "type": "Array<PricingTablesResponseTables>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTablesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

