/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableRequestRowDataDiscount } from './PricingTableRequestRowDataDiscount';
import { PricingTableRequestRowDataTaxFirst } from './PricingTableRequestRowDataTaxFirst';
import { PricingTableRequestRowDataTaxSecond } from './PricingTableRequestRowDataTaxSecond';
import { HttpFile } from '../http/http';

export class PricingTableRequestRowData {
    'name': string;
    'description'?: string;
    'price': number;
    'cost'?: number;
    'qty': number;
    'sku'?: string;
    'discount'?: PricingTableRequestRowDataDiscount;
    'taxFirst'?: PricingTableRequestRowDataTaxFirst;
    'taxSecond'?: PricingTableRequestRowDataTaxSecond;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "PricingTableRequestRowDataDiscount",
            "format": ""
        },
        {
            "name": "taxFirst",
            "baseName": "tax_first",
            "type": "PricingTableRequestRowDataTaxFirst",
            "format": ""
        },
        {
            "name": "taxSecond",
            "baseName": "tax_second",
            "type": "PricingTableRequestRowDataTaxSecond",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestRowData.attributeTypeMap;
    }

    public constructor() {
    }
}

