/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingTableRequestRows } from './PricingTableRequestRows';
import { HttpFile } from '../http/http';

export class PricingTableRequestSections {
    'title'?: string;
    '_default'?: boolean;
    'multichoiceEnabled'?: boolean;
    'rows'?: Array<PricingTableRequestRows>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "multichoiceEnabled",
            "baseName": "multichoice_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rows",
            "baseName": "rows",
            "type": "Array<PricingTableRequestRows>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestSections.attributeTypeMap;
    }

    public constructor() {
    }
}

