/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PricingTableRequestOptions1 {
    'qtyEditable'?: boolean;
    'optionalSelected'?: boolean;
    'optional'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "qtyEditable",
            "baseName": "qty_editable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "optionalSelected",
            "baseName": "optional_selected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingTableRequestOptions1.attributeTypeMap;
    }

    public constructor() {
    }
}

