/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemPatchRequestBundleItemsInnerItemOrUuid } from '../models/ProductCatalogItemPatchRequestBundleItemsInnerItemOrUuid';
import { HttpFile } from '../http/http';

export class ProductCatalogItemPatchRequestBundleItemsInner {
    'quantity'?: number;
    'itemOrUuid'?: ProductCatalogItemPatchRequestBundleItemsInnerItemOrUuid;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "itemOrUuid",
            "baseName": "item_or_uuid",
            "type": "ProductCatalogItemPatchRequestBundleItemsInnerItemOrUuid",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemPatchRequestBundleItemsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
