/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemPriceTier } from '../models/ProductCatalogItemPriceTier';
import { HttpFile } from '../http/http';

export class ProductCatalogItemResponseDefaultPriceConfiguration {
    'currency': string;
    'price'?: number | null;
    'cost'?: number | null;
    'billingType'?: string;
    'billingCycle'?: string | null;
    /**
    * only for volume based pricing
    */
    'tiers'?: Array<ProductCatalogItemPriceTier> | null;
    'pricingMethod': number;
    'uuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "billingType",
            "baseName": "billing_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingCycle",
            "baseName": "billing_cycle",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "Array<ProductCatalogItemPriceTier>",
            "format": ""
        },
        {
            "name": "pricingMethod",
            "baseName": "pricing_method",
            "type": "number",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemResponseDefaultPriceConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
