/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemResponseBundleItemsInnerItem } from '../models/ProductCatalogItemResponseBundleItemsInnerItem';
import { HttpFile } from '../http/http';

export class ProductCatalogItemResponseBundleItemsInner {
    'quantity'?: number;
    'item'?: ProductCatalogItemResponseBundleItemsInnerItem;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "ProductCatalogItemResponseBundleItemsInnerItem",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemResponseBundleItemsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
