/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductCatalogItemPriceTier {
    'value': number;
    'minQty': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "minQty",
            "baseName": "min_qty",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemPriceTier.attributeTypeMap;
    }

    public constructor() {
    }
}
