/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemPriceConfiguration } from '../models/ProductCatalogItemPriceConfiguration';
import { ProductCatalogItemRequestBundleItemsInner } from '../models/ProductCatalogItemRequestBundleItemsInner';
import { ProductCatalogItemRequestCustomFieldsInner } from '../models/ProductCatalogItemRequestCustomFieldsInner';
import { ProductCatalogItemRequestImagesInner } from '../models/ProductCatalogItemRequestImagesInner';
import { ProductCatalogTypeEnum } from '../models/ProductCatalogTypeEnum';
import { HttpFile } from '../http/http';

export class ProductCatalogItemRequest {
    'title': string;
    'categoryId'?: string | null;
    'sku'?: string | null;
    'description'?: string | null;
    'type'?: ProductCatalogTypeEnum;
    'bundleItems'?: Array<ProductCatalogItemRequestBundleItemsInner> | null;
    'images'?: Array<ProductCatalogItemRequestImagesInner> | null;
    'customFields'?: Array<ProductCatalogItemRequestCustomFieldsInner> | null;
    'priceConfiguration': ProductCatalogItemPriceConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductCatalogTypeEnum",
            "format": ""
        },
        {
            "name": "bundleItems",
            "baseName": "bundle_items",
            "type": "Array<ProductCatalogItemRequestBundleItemsInner>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductCatalogItemRequestImagesInner>",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<ProductCatalogItemRequestCustomFieldsInner>",
            "format": ""
        },
        {
            "name": "priceConfiguration",
            "baseName": "price_configuration",
            "type": "ProductCatalogItemPriceConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


