/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemPriceConfiguration } from '../models/ProductCatalogItemPriceConfiguration';
import { ProductCatalogItemRequestImagesInner } from '../models/ProductCatalogItemRequestImagesInner';
import { ProductCatalogSearchCatalogItemResponseCustomFieldsInner } from '../models/ProductCatalogSearchCatalogItemResponseCustomFieldsInner';
import { HttpFile } from '../http/http';

export class ProductCatalogItemPatchRequestProductVariant {
    'sku'?: string | null;
    'description'?: string | null;
    'images'?: Array<ProductCatalogItemRequestImagesInner> | null;
    'customFields'?: Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner> | null;
    'priceConfiguration'?: ProductCatalogItemPriceConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductCatalogItemRequestImagesInner>",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner>",
            "format": ""
        },
        {
            "name": "priceConfiguration",
            "baseName": "price_configuration",
            "type": "ProductCatalogItemPriceConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemPatchRequestProductVariant.attributeTypeMap;
    }

    public constructor() {
    }
}
