/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogSearchCatalogItemResponseCustomFieldsInner } from '../models/ProductCatalogSearchCatalogItemResponseCustomFieldsInner';
import { ProductCatalogSearchCatalogItemResponseImagesInner } from '../models/ProductCatalogSearchCatalogItemResponseImagesInner';
import { ProductCatalogSearchCatalogItemResponseTiersInner } from '../models/ProductCatalogSearchCatalogItemResponseTiersInner';
import { ProductCatalogTypeEnum } from '../models/ProductCatalogTypeEnum';
import { HttpFile } from '../http/http';

export class ProductCatalogSearchCatalogItemResponse {
    'billingCycle'?: number | null;
    'billingType'?: string;
    'bundleItemsCount'?: number;
    'workspaceId'?: string;
    'categoryId'?: string | null;
    'categoryName'?: string | null;
    'createdBy'?: string;
    'cost'?: number | null;
    'currency'?: string;
    'customFields'?: Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner> | null;
    'dateCreated'?: Date;
    'dateModified'?: Date | null;
    'description'?: string | null;
    'imageSrc'?: string | null;
    'images'?: Array<ProductCatalogSearchCatalogItemResponseImagesInner> | null;
    'maxTierValue'?: number | null;
    'minTierValue'?: number | null;
    'modifiedBy'?: string;
    'price'?: number | null;
    'pricingMethod'?: number;
    'sku'?: string;
    'title'?: string;
    'tiers'?: Array<ProductCatalogSearchCatalogItemResponseTiersInner> | null;
    'type'?: ProductCatalogTypeEnum;
    'uuid'?: string;
    'highlights'?: { [key: string]: any; } | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingCycle",
            "baseName": "billing_cycle",
            "type": "number",
            "format": ""
        },
        {
            "name": "billingType",
            "baseName": "billing_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "bundleItemsCount",
            "baseName": "bundle_items_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryName",
            "baseName": "category_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner>",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageSrc",
            "baseName": "image_src",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductCatalogSearchCatalogItemResponseImagesInner>",
            "format": ""
        },
        {
            "name": "maxTierValue",
            "baseName": "max_tier_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "minTierValue",
            "baseName": "min_tier_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "modifiedBy",
            "baseName": "modified_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "pricingMethod",
            "baseName": "pricing_method",
            "type": "number",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "Array<ProductCatalogSearchCatalogItemResponseTiersInner>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductCatalogTypeEnum",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "highlights",
            "baseName": "highlights",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogSearchCatalogItemResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


