/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogCatalogCustomBundleItem } from '../models/ProductCatalogCatalogCustomBundleItem';
import { HttpFile } from '../http/http';

/**
 * @type ProductCatalogItemRequestBundleItemsInnerItemOrUuid
 * Type
 * @export
 */
export type ProductCatalogItemRequestBundleItemsInnerItemOrUuid = ProductCatalogCatalogCustomBundleItem | string;

/**
* @type ProductCatalogItemRequestBundleItemsInnerItemOrUuidClass
* @export
*/
export class ProductCatalogItemRequestBundleItemsInnerItemOrUuidClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

