/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemPatchRequestBundleItemsInner } from '../models/ProductCatalogItemPatchRequestBundleItemsInner';
import { ProductCatalogItemPatchRequestProductVariant } from '../models/ProductCatalogItemPatchRequestProductVariant';
import { ProductCatalogTypeEnum } from '../models/ProductCatalogTypeEnum';
import { HttpFile } from '../http/http';

export class ProductCatalogItemPatchRequest {
    'title'?: string;
    'categoryId'?: string | null;
    'type'?: ProductCatalogTypeEnum;
    'bundleItems'?: Array<ProductCatalogItemPatchRequestBundleItemsInner> | null;
    'productVariant'?: ProductCatalogItemPatchRequestProductVariant;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductCatalogTypeEnum",
            "format": ""
        },
        {
            "name": "bundleItems",
            "baseName": "bundle_items",
            "type": "Array<ProductCatalogItemPatchRequestBundleItemsInner>",
            "format": ""
        },
        {
            "name": "productVariant",
            "baseName": "product_variant",
            "type": "ProductCatalogItemPatchRequestProductVariant",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemPatchRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


