/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductCatalogSearchCatalogItemResponseImagesInner {
    'isMain'?: boolean | null;
    'order'?: number;
    'src'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isMain",
            "baseName": "is_main",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": ""
        },
        {
            "name": "src",
            "baseName": "src",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogSearchCatalogItemResponseImagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}
