/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductCatalogItemResponseDefaultPriceConfiguration } from '../models/ProductCatalogItemResponseDefaultPriceConfiguration';
import { ProductCatalogSearchCatalogItemResponseCustomFieldsInner } from '../models/ProductCatalogSearchCatalogItemResponseCustomFieldsInner';
import { ProductCatalogSearchCatalogItemResponseImagesInner } from '../models/ProductCatalogSearchCatalogItemResponseImagesInner';
import { HttpFile } from '../http/http';

export class ProductCatalogItemResponseVariantsInner {
    'uuid'?: string;
    'sku'?: string | null;
    'description'?: string | null;
    'customFields'?: Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner> | null;
    'images'?: Array<ProductCatalogSearchCatalogItemResponseImagesInner> | null;
    'dateCreated'?: Date;
    'dateModified'?: Date | null;
    'status'?: number;
    'priceConfigurations'?: Array<ProductCatalogItemResponseDefaultPriceConfiguration>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<ProductCatalogSearchCatalogItemResponseCustomFieldsInner>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductCatalogSearchCatalogItemResponseImagesInner>",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceConfigurations",
            "baseName": "price_configurations",
            "type": "Array<ProductCatalogItemResponseDefaultPriceConfiguration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCatalogItemResponseVariantsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
