/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicV1DocumentsContentLibraryItems } from './PublicV1DocumentsContentLibraryItems';
import { HttpFile } from '../http/http';

export class PublicV1DocumentsContentPlaceholders {
    /**
    * Content placeholder block id
    */
    'blockId'?: string;
    'contentLibraryItems'?: Array<PublicV1DocumentsContentLibraryItems>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockId",
            "baseName": "block_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentLibraryItems",
            "baseName": "content_library_items",
            "type": "Array<PublicV1DocumentsContentLibraryItems>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicV1DocumentsContentPlaceholders.attributeTypeMap;
    }

    public constructor() {
    }
}

