/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteUpdateRequestPriceSettingsTiers } from './QuoteUpdateRequestPriceSettingsTiers';
import { HttpFile } from '../http/http';

/**
* Price settings if the price is not flat rate. If it is null, the price is flat rate.
*/
export class QuoteUpdateRequestPriceSettings {
    /**
    * Base value for volume discount pricing. If set, tiers are treated like percentage of discount on this value. If not set, tiers are treated like a flat value discount of chosen currency.
    */
    'baseValue': number;
    'tiers': Array<QuoteUpdateRequestPriceSettingsTiers>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseValue",
            "baseName": "base_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "Array<QuoteUpdateRequestPriceSettingsTiers>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteUpdateRequestPriceSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

