/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteResponseMergeRulesInnerConditionComparisonInner } from '../models/QuoteResponseMergeRulesInnerConditionComparisonInner';
import { HttpFile } from '../http/http';

export class QuoteResponseMergeRulesInnerCondition {
    'fieldName'?: string;
    'type'?: string;
    'comparison'?: Array<QuoteResponseMergeRulesInnerConditionComparisonInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "comparison",
            "baseName": "comparison",
            "type": "Array<QuoteResponseMergeRulesInnerConditionComparisonInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseMergeRulesInnerCondition.attributeTypeMap;
    }

    public constructor() {
    }
}
