/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteUpdateRequestSettings } from '../models/QuoteUpdateRequestSettings';
import { UpdateIntegrationQuoteSection } from '../models/UpdateIntegrationQuoteSection';
import { HttpFile } from '../http/http';

export class QuoteUpdateRequest {
    /**
    * Currency code (ISO 4217)
    */
    'currency'?: string;
    /**
    * Quote sections - this property overrides existing sections in the specified order. If you want to change only one section, you must still pass other sections IDs. Otherwise these sections will be removed.
    */
    'sections'?: Array<UpdateIntegrationQuoteSection>;
    'settings'?: QuoteUpdateRequestSettings;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<UpdateIntegrationQuoteSection>",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "QuoteUpdateRequestSettings",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
