/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteResponseOptions } from './QuoteResponseOptions';
import { QuoteResponseSummaryDiscounts } from './QuoteResponseSummaryDiscounts';
import { HttpFile } from '../http/http';

export class QuoteResponseSectionItem {
    'id'?: string;
    'sku'?: string;
    'name'?: string;
    'description'?: string;
    'qty'?: string;
    'price'?: string;
    'cost'?: string;
    'billingFrequency'?: string;
    'contractTerm'?: string;
    'pricingMethod'?: string;
    'type'?: string;
    'referenceType'?: string;
    'options'?: QuoteResponseOptions;
    'customColumns'?: { [key: string]: string; };
    'discounts'?: { [key: string]: QuoteResponseSummaryDiscounts; };
    'taxes'?: { [key: string]: QuoteResponseSummaryDiscounts; };
    'fees'?: { [key: string]: QuoteResponseSummaryDiscounts; };
    'multipliers'?: { [key: string]: string; };
    'total'?: string;
    'overallTotal'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingFrequency",
            "baseName": "billing_frequency",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractTerm",
            "baseName": "contract_term",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricingMethod",
            "baseName": "pricing_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceType",
            "baseName": "reference_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "QuoteResponseOptions",
            "format": ""
        },
        {
            "name": "customColumns",
            "baseName": "custom_columns",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "{ [key: string]: QuoteResponseSummaryDiscounts; }",
            "format": ""
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "{ [key: string]: QuoteResponseSummaryDiscounts; }",
            "format": ""
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "{ [key: string]: QuoteResponseSummaryDiscounts; }",
            "format": ""
        },
        {
            "name": "multipliers",
            "baseName": "multipliers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "overallTotal",
            "baseName": "overall_total",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseSectionItem.attributeTypeMap;
    }

    public constructor() {
    }
}

