/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteResponseAction } from './QuoteResponseAction';
import { QuoteResponseCondition } from './QuoteResponseCondition';
import { HttpFile } from '../http/http';

export class QuoteResponseMergeRules {
    'id'?: string;
    'enabled'?: boolean;
    'action'?: QuoteResponseAction;
    'condition'?: QuoteResponseCondition;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "QuoteResponseAction",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "QuoteResponseCondition",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseMergeRules.attributeTypeMap;
    }

    public constructor() {
    }
}

