/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class QuoteResponseSectionColumn {
    'header'?: string | null;
    'name'?: string;
    'mergeName'?: string | null;
    'hidden'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "header",
            "baseName": "header",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "mergeName",
            "baseName": "merge_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseSectionColumn.attributeTypeMap;
    }

    public constructor() {
    }
}
