/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteUpdateRequestSettingsSelectionTypeTypeEnum } from '../models/QuoteUpdateRequestSettingsSelectionTypeTypeEnum';
import { HttpFile } from '../http/http';

/**
* Quote settings. Denotes whether a quote is optional or selected, and selection type inside the section - single, multiple, or custom.
*/
export class QuoteUpdateRequestSettings {
    'selectionType'?: QuoteUpdateRequestSettingsSelectionTypeTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "selectionType",
            "baseName": "selection_type",
            "type": "QuoteUpdateRequestSettingsSelectionTypeTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteUpdateRequestSettings.attributeTypeMap;
    }

    public constructor() {
    }
}


