/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class QuoteResponseSectionItemOptions {
    'selected'?: boolean | null;
    'qtyEditable'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "selected",
            "baseName": "selected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "qtyEditable",
            "baseName": "qty_editable",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseSectionItemOptions.attributeTypeMap;
    }

    public constructor() {
    }
}
