/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteResponseMergeRulesInner } from '../models/QuoteResponseMergeRulesInner';
import { QuoteResponseSectionsInner } from '../models/QuoteResponseSectionsInner';
import { QuoteResponseSettings } from '../models/QuoteResponseSettings';
import { QuoteResponseSummary } from '../models/QuoteResponseSummary';
import { HttpFile } from '../http/http';

export class QuoteResponse {
    'id'?: string;
    'currency'?: string;
    'total'?: string;
    'summary'?: QuoteResponseSummary;
    'sections'?: Array<QuoteResponseSectionsInner>;
    'mergeRules'?: Array<QuoteResponseMergeRulesInner>;
    'settings'?: QuoteResponseSettings;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "QuoteResponseSummary",
            "format": ""
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<QuoteResponseSectionsInner>",
            "format": ""
        },
        {
            "name": "mergeRules",
            "baseName": "merge_rules",
            "type": "Array<QuoteResponseMergeRulesInner>",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "QuoteResponseSettings",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
