/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteResponseConditionComparison } from './QuoteResponseConditionComparison';
import { HttpFile } from '../http/http';

export class QuoteResponseCondition {
    'fieldName'?: string;
    'type'?: string;
    'comparison'?: Array<QuoteResponseConditionComparison>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "comparison",
            "baseName": "comparison",
            "type": "Array<QuoteResponseConditionComparison>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuoteResponseCondition.attributeTypeMap;
    }

    public constructor() {
    }
}

