/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecipientVerificationSettingsPasscodeVerification } from './RecipientVerificationSettingsPasscodeVerification';
import { RecipientVerificationSettingsPhoneVerification } from './RecipientVerificationSettingsPhoneVerification';
import { HttpFile } from '../http/http';

export class RecipientVerificationSettings {
    /**
    * Verification place
    */
    'verificationPlace'?: RecipientVerificationSettingsVerificationPlaceEnum;
    'passcodeVerification'?: RecipientVerificationSettingsPasscodeVerification;
    'phoneVerification'?: RecipientVerificationSettingsPhoneVerification;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "verificationPlace",
            "baseName": "verification_place",
            "type": "RecipientVerificationSettingsVerificationPlaceEnum",
            "format": ""
        },
        {
            "name": "passcodeVerification",
            "baseName": "passcode_verification",
            "type": "RecipientVerificationSettingsPasscodeVerification",
            "format": ""
        },
        {
            "name": "phoneVerification",
            "baseName": "phone_verification",
            "type": "RecipientVerificationSettingsPhoneVerification",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecipientVerificationSettings.attributeTypeMap;
    }

    public constructor() {
    }
}


export type RecipientVerificationSettingsVerificationPlaceEnum = "before_open" | "before_sign" ;

