/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Sets the KBA verification.
*/
export class RecipientVerificationSettingsKbaVerification {
    'timeLimitSec'?: number;
    'scoreThreshold'?: number;
    'maxAttemptsCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeLimitSec",
            "baseName": "time_limit_sec",
            "type": "number",
            "format": ""
        },
        {
            "name": "scoreThreshold",
            "baseName": "score_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxAttemptsCount",
            "baseName": "max_attempts_count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecipientVerificationSettingsKbaVerification.attributeTypeMap;
    }

    public constructor() {
    }
}
