/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Sets the phone number to send a passcode to.
*/
export class RecipientVerificationSettingsPhoneVerification {
    /**
    * A phone number to send a passcode to.
    */
    'phoneNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecipientVerificationSettingsPhoneVerification.attributeTypeMap;
    }

    public constructor() {
    }
}
