/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Specifies when a recipient must complete the verification process: - `before_open` (before opening the document), - `before_sign` (before signing the document). 
*/
export enum RecipientVerificationPlaceEnum {
    BeforeOpen = 'before_open',
    BeforeSign = 'before_sign'
}
