/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RicipientDeliveryMethods {
    'email'?: boolean;
    'sms'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sms",
            "baseName": "sms",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RicipientDeliveryMethods.attributeTypeMap;
    }

    public constructor() {
    }
}

