/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SectionInfoResponse {
    'uuid'?: string;
    'name'?: string;
    'documentUuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentUuid",
            "baseName": "document_uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SectionInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

