/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TableCell } from '../models/TableCell';
import { HttpFile } from '../http/http';

export class TableRequestDataSectionsInner {
    'header': Array<TableCell>;
    'rows': Array<Array<TableCell>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "header",
            "baseName": "header",
            "type": "Array<TableCell>",
            "format": ""
        },
        {
            "name": "rows",
            "baseName": "rows",
            "type": "Array<Array<TableCell>>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableRequestDataSectionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
