/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentUpdateRequestTokensInner } from '../models/DocumentUpdateRequestTokensInner';
import { HttpFile } from '../http/http';

export class TemplateUpdateRequest {
    /**
    * Create or initialize multiple CUSTOM variables with their values using tokens/values list. Template\'s predefined variables are read-only. Any attempts to do so will be ignored.
    */
    'tokens'?: Array<DocumentUpdateRequestTokensInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<DocumentUpdateRequestTokensInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
