/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentLibraryItemResponseCreatedBy } from '../models/ContentLibraryItemResponseCreatedBy';
import { DocumentDetailsResponseTablesInner } from '../models/DocumentDetailsResponseTablesInner';
import { PricingResponse } from '../models/PricingResponse';
import { TemplateDetailsResponseContentPlaceholdersInner } from '../models/TemplateDetailsResponseContentPlaceholdersInner';
import { TemplateDetailsResponseImagesInner } from '../models/TemplateDetailsResponseImagesInner';
import { TemplateDetailsResponseRolesInner } from '../models/TemplateDetailsResponseRolesInner';
import { TemplateDetailsResponseTokensInner } from '../models/TemplateDetailsResponseTokensInner';
import { HttpFile } from '../http/http';

export class TemplateDetailsResponse {
    'id'?: string;
    'name'?: string;
    'folderUuid'?: string;
    'dateCreated'?: string;
    'dateModified'?: string;
    'contentDateModified'?: string;
    'createdBy'?: ContentLibraryItemResponseCreatedBy;
    'metadata'?: any;
    'tokens'?: Array<TemplateDetailsResponseTokensInner>;
    'fields'?: Array<any>;
    'pricing'?: PricingResponse;
    'tags'?: Array<string>;
    'roles'?: Array<TemplateDetailsResponseRolesInner>;
    'version'?: string;
    'contentPlaceholders'?: Array<TemplateDetailsResponseContentPlaceholdersInner>;
    /**
    * Document tables.
    */
    'tables'?: Array<DocumentDetailsResponseTablesInner>;
    'images'?: Array<TemplateDetailsResponseImagesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "folderUuid",
            "baseName": "folder_uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentDateModified",
            "baseName": "content_date_modified",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "ContentLibraryItemResponseCreatedBy",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<TemplateDetailsResponseTokensInner>",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "PricingResponse",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<TemplateDetailsResponseRolesInner>",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentPlaceholders",
            "baseName": "content_placeholders",
            "type": "Array<TemplateDetailsResponseContentPlaceholdersInner>",
            "format": ""
        },
        {
            "name": "tables",
            "baseName": "tables",
            "type": "Array<DocumentDetailsResponseTablesInner>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<TemplateDetailsResponseImagesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateDetailsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
