/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecipientDeliveryMethods } from '../models/RecipientDeliveryMethods';
import { RecipientRedirect } from '../models/RecipientRedirect';
import { HttpFile } from '../http/http';

export class UpdateDocumentRecipient {
    /**
    * A recipient\'s role in the document from the template. A recipient will be added in CC if a role parameter is not provided.
    */
    'role'?: string;
    /**
    * Set a signing order for a recipient. Learn more: https://developers.pandadoc.com/docs/set-signing-order 
    */
    'signingOrder'?: number;
    /**
    * A recipient\'s email address.
    */
    'email'?: string | null;
    /**
    * A recipient\'s phone number.
    */
    'phone'?: string | null;
    /**
    * A recipient\'s first name. We automatically take the first name from contact data if this field is missed.
    */
    'firstName'?: string;
    /**
    * A recipient\'s last name. We automatically take the last name from contact data if this field is missed.
    */
    'lastName'?: string;
    'id'?: string;
    'deliveryMethods'?: RecipientDeliveryMethods | null;
    'redirect'?: RecipientRedirect;
    'type'?: UpdateDocumentRecipientTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingOrder",
            "baseName": "signing_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryMethods",
            "baseName": "delivery_methods",
            "type": "RecipientDeliveryMethods",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "RecipientRedirect",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpdateDocumentRecipientTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateDocumentRecipient.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateDocumentRecipientTypeEnum {
    Recipient = 'recipient'
}

