/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentDeliveryMethodEnum } from '../models/DocumentDeliveryMethodEnum';
import { HttpFile } from '../http/http';

export class UpdateDocumentAutoRemindersRequest {
    /**
    * Toggles auto-reminders for the document.  If `true`, reminders are scheduled based on the configuration. 
    */
    'enabled': boolean;
    'deliveryMethod'?: DocumentDeliveryMethodEnum;
    /**
    * Number of days to wait after sending the document before the first reminder is sent. 
    */
    'initialDelayDays'?: number;
    /**
    * If `true`, reminders will be sent repeatedly at specified intervals after the initial reminder. 
    */
    'isRecurring'?: boolean;
    /**
    * Number of days between recurring reminders, applicable if `is_recurring` is `true`. 
    */
    'recurrenceFrequencyDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deliveryMethod",
            "baseName": "delivery_method",
            "type": "DocumentDeliveryMethodEnum",
            "format": ""
        },
        {
            "name": "initialDelayDays",
            "baseName": "initial_delay_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "isRecurring",
            "baseName": "is_recurring",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "recurrenceFrequencyDays",
            "baseName": "recurrence_frequency_days",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateDocumentAutoRemindersRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


