/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentLanguageEnum } from '../models/DocumentLanguageEnum';
import { HttpFile } from '../http/http';

/**
* Template settings update request.
*/
export class UpdateTemplateSettingsRequest {
    'language'?: DocumentLanguageEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "language",
            "baseName": "language",
            "type": "DocumentLanguageEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateTemplateSettingsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


