/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuoteUpdateRequestBillingFrequencyEnum } from '../models/QuoteUpdateRequestBillingFrequencyEnum';
import { UpdateIntegrationQuoteSectionItemDiscountsValue } from '../models/UpdateIntegrationQuoteSectionItemDiscountsValue';
import { UpdateIntegrationQuoteSectionItemOptions } from '../models/UpdateIntegrationQuoteSectionItemOptions';
import { UpdateIntegrationQuoteSectionItemPriceSettings } from '../models/UpdateIntegrationQuoteSectionItemPriceSettings';
import { HttpFile } from '../http/http';

export class UpdateIntegrationQuoteSectionItem {
    /**
    * Item ID to update. Invalid (or missing) ID causes creating a new item.
    */
    'id'?: string;
    /**
    * Product SKU. If you create an item without providing a value, it will have the default value.
    */
    'sku'?: string;
    /**
    * Item name. If you create an item without providing a value, it will have the default value.
    */
    'name'?: string;
    /**
    * Item description. If you create an item without providing a value, it will have the default value.
    */
    'description'?: string;
    /**
    * Item QTY. If you create an item without providing a value, it will have the default value.
    */
    'qty'?: number;
    /**
    * Item price. If you create an item without providing a value, it will have the default value. If `price_settings` is passed, this value may change after the quote is updated.
    */
    'price'?: number;
    'priceSettings'?: UpdateIntegrationQuoteSectionItemPriceSettings;
    /**
    * Item cost. If you create an item without providing a value, it will have the default value.
    */
    'cost'?: number;
    'billingFrequency'?: QuoteUpdateRequestBillingFrequencyEnum | null;
    /**
    * Contract term. Measured in units set in the `billing_frequency` parameter.
    */
    'contractTerm'?: number | null;
    /**
    * Use this field to pass an id that references this item in external systems.
    */
    'referenceId'?: string | null;
    'options'?: UpdateIntegrationQuoteSectionItemOptions;
    'customColumns'?: { [key: string]: string; };
    'externalColumns'?: { [key: string]: string; };
    'textColumns'?: { [key: string]: string; };
    /**
    * Item discounts.
    */
    'discounts'?: { [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; };
    /**
    * Item taxes.
    */
    'taxes'?: { [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; };
    /**
    * Item fees.
    */
    'fees'?: { [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; };
    /**
    * Item multipliers.
    */
    'multipliers'?: { [key: string]: number; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceSettings",
            "baseName": "price_settings",
            "type": "UpdateIntegrationQuoteSectionItemPriceSettings",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "billingFrequency",
            "baseName": "billing_frequency",
            "type": "QuoteUpdateRequestBillingFrequencyEnum",
            "format": ""
        },
        {
            "name": "contractTerm",
            "baseName": "contract_term",
            "type": "number",
            "format": ""
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "UpdateIntegrationQuoteSectionItemOptions",
            "format": ""
        },
        {
            "name": "customColumns",
            "baseName": "custom_columns",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "externalColumns",
            "baseName": "external_columns",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "textColumns",
            "baseName": "text_columns",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "{ [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; }",
            "format": ""
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "{ [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; }",
            "format": ""
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "{ [key: string]: UpdateIntegrationQuoteSectionItemDiscountsValue; }",
            "format": ""
        },
        {
            "name": "multipliers",
            "baseName": "multipliers",
            "type": "{ [key: string]: number; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateIntegrationQuoteSectionItem.attributeTypeMap;
    }

    public constructor() {
    }
}


