/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateDocumentActor } from '../models/CreateDocumentActor';
import { DocumentUpdateRequestTokensInner } from '../models/DocumentUpdateRequestTokensInner';
import { HttpFile } from '../http/http';

export class UploadSectionBase {
    /**
    * Name the document you are creating.
    */
    'name'?: string;
    /**
    * The list of recipients you\'re sending the document to. Every object must contain the `email` parameter. The `role`, `first_name` and `last_name` parameters are optional. If the `role` parameter is passed, a person is assigned all fields matching their corresponding role. If a role was not passed, a person receives a read-only link to view the document. If the `first_name` and `last_name` are not passed, the system does this 1. Creates a new contact, if none exists with the given `email`; or 2. Gets the existing contact with the given `email` that already exists.
    */
    'recipients': Array<CreateDocumentActor>;
    /**
    * You may pass a list of tokens/values to pre-fill tokens (variables) used in a template. Name is a token (variable) name in a template. Value is a real value you would like to replace a token (variable) with. 
    */
    'tokens'?: Array<DocumentUpdateRequestTokensInner>;
    /**
    * Mark your document with one or several tags.
    */
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<CreateDocumentActor>",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<DocumentUpdateRequestTokensInner>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadSectionBase.attributeTypeMap;
    }

    public constructor() {
    }
}
