/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type UploadSectionStatusEnum = "document_sections_upload.UPLOADED" | "document_sections_upload.PROCESSED" | "document_sections_upload.ERROR" ;
