/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UploadSectionByTemplateRequestAllOfContentLibraryItems } from '../models/UploadSectionByTemplateRequestAllOfContentLibraryItems';
import { HttpFile } from '../http/http';

export class UploadSectionByTemplateRequestAllOfContentPlaceholders {
    'contentLibraryItems'?: Array<UploadSectionByTemplateRequestAllOfContentLibraryItems>;
    'blockId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentLibraryItems",
            "baseName": "content_library_items",
            "type": "Array<UploadSectionByTemplateRequestAllOfContentLibraryItems>",
            "format": ""
        },
        {
            "name": "blockId",
            "baseName": "block_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadSectionByTemplateRequestAllOfContentPlaceholders.attributeTypeMap;
    }

    public constructor() {
    }
}
