/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum WebhookEventErrorEnum {
    InternalError = 'INTERNAL_ERROR',
    NotValidUrl = 'NOT_VALID_URL',
    ConnectError = 'CONNECT_ERROR',
    TimeoutError = 'TIMEOUT_ERROR'
}
