/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebhookSubscriptionItemResponse } from './WebhookSubscriptionItemResponse';
import { HttpFile } from '../http/http';

export class WebhookSubscriptionListResponse {
    'items'?: Array<WebhookSubscriptionItemResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<WebhookSubscriptionItemResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookSubscriptionListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

