/**
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebhookEventItemResponse } from '../models/WebhookEventItemResponse';
import { HttpFile } from '../http/http';

export class WebhookEventPageResponse {
    'items'?: Array<WebhookEventItemResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<WebhookEventItemResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookEventPageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
